// Generated by CoffeeScript 1.4.0
var Category, Entity, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Entity = require("./entity");

_ = require("underscore");

module.exports = Category = (function(_super) {

  __extends(Category, _super);

  function Category() {
    return Category.__super__.constructor.apply(this, arguments);
  }

  /**
   * @type {String}
  */


  Category.resource = "categories";

  return Category;

})(Entity);

/**
 * Defining the properties
*/


["_id", "name", "slug", "parent", "label"].forEach(function(property) {
  return Object.defineProperty(Category.prototype, property, {
    get: function() {
      return this._data[property];
    },
    set: function(v) {
      return this._data[property] = v;
    }
  });
});
