// Generated by CoffeeScript 1.4.0
var Cause, Entity, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Entity = require("./entity");

_ = require("underscore");

module.exports = Cause = (function(_super) {

  __extends(Cause, _super);

  function Cause() {
    return Cause.__super__.constructor.apply(this, arguments);
  }

  /**
   * @type {String}
  */


  Cause.resource = "causes";

  return Cause;

})(Entity);

/**
 * Defining the properties
*/


["_id", "name", "description", "restrictions", "imageSquare", "url"].forEach(function(property) {
  return Object.defineProperty(Cause.prototype, property, {
    get: function() {
      return this._data[property];
    },
    set: function(v) {
      return this._data[property] = v;
    }
  });
});
