// Generated by CoffeeScript 1.4.0

module.exports = function(response, entity) {
  var data;
  data = [];
  response.data.forEach(function(obj) {
    return data.push(new entity(obj));
  });
  return data;
};
