// Generated by CoffeeScript 1.4.0
var Category, Cause, FraisrAPI, Product, _;

_ = require("underscore");

FraisrAPI = (function() {

  FraisrAPI.prototype.key = null;

  FraisrAPI.prototype.secret = null;

  FraisrAPI.prototype.url = null;

  FraisrAPI.prototype.mode = "live";

  FraisrAPI.prototype.version = 1;

  FraisrAPI.prototype.modes = {
    live: "https://www.fraisr.com",
    sandbox: "https://fraisr-test.herokuapp.com"
  };

  /**
   * @constructor
   * @param  {String} key     API key
   * @param  {String} secret  API secret
   * @param  {String} mode    live oder sandbox mode
   * @param  {String} url     API url; Should not be necessary
  */


  function FraisrAPI(key, secret, mode, version, url) {
    var _ref, _ref1, _ref2;
    this.key = key;
    this.secret = secret;
    this.mode = mode != null ? mode : "live";
    this.version = version != null ? version : 1;
    this.url = url != null ? url : null;
    if (!((_ref = this.key) != null ? _ref.length : void 0)) {
      throw new Error("Please provide an API key.");
    }
    if (!((_ref1 = this.secret) != null ? _ref1.length : void 0)) {
      throw new Error("Please provide an API secret.");
    }
    if (!((this.mode != null) && (this.modes[this.mode] != null))) {
      throw new Error(("Mode " + this.mode + " does not exists, please use one of the following: ") + Object.keys(this.modes).join(", "));
    }
    if (!((_ref2 = this.url) != null ? _ref2.length : void 0)) {
      this.url = this.modes[this.mode];
    }
    this.url += "/api/v" + this.version;
  }

  /**
   * @see Entity.list
   * @param  {Function} callback 
   * @param  {Object}   params
  */


  FraisrAPI.prototype.getCategories = function(callback, params) {
    if (params == null) {
      params = {};
    }
    return Category.list(this, callback, params);
  };

  /**
   * @see Entity.lookup
   * @param  {String}   id
   * @param  {Function} callback 
   * @notImplemented
  */


  /**
   * @see Entity.list
   * @param  {Function} callback 
   * @param  {Object}   params
  */


  FraisrAPI.prototype.getCauses = function(callback, params) {
    if (params == null) {
      params = {};
    }
    return Cause.list(this, callback, params);
  };

  /**
   * @see Entity.list
   * @param  {Function} callback 
   * @param  {Object}   params
  */


  FraisrAPI.prototype.getProducts = function(callback, params) {
    if (params == null) {
      params = {};
    }
    return Product.list(this, callback, params);
  };

  /**
   * @see Entity.lookup
   * @param  {String}   id
   * @param  {Function} callback
  */


  FraisrAPI.prototype.getProduct = function(id, callback) {
    return Product.lookup(this, callback, id);
  };

  return FraisrAPI;

})();

module.exports = FraisrAPI;

module.exports.Category = Category = require("./category");

module.exports.Cause = Cause = require("./cause");

module.exports.Product = Product = require("./product");
